### ISSUE TITLE
Mark packages out of date

### ISSUE THREAD

**Issue by Trollwut** [XenGi/pac#16] opened 2017-11-23 20:14 UTC
Hi folks!

If you search the AUR, there is no indicator if a package is up-to-date or not. E.g. the package `ark-desktop` is currently marked as out-of-date in the AUR, `xfce-theme-blackbird` is up-to-date:

- [`pac ark desktop`](https://i.imgur.com/Ar4ueHv.png)
- [`pacaur -Ss ark desktop`](https://i.imgur.com/sW96p5p.png)

In the latter, an out-of-date package is being marked by a red version number. In `yaourt`, it is written, that it's out-of-date.

**Comment by xnick** [comment] 2017-11-23 20:28
This is covered by #9. It looks like @XenGi has abandoned this project though. 

If you want, take a look at my [fork](https://github.com/xnick/pac), I have merged many of the PR's here and implemented flag passthrough to pacaur.

**Comment by Trollwut** [comment] 2017-11-23 20:31
Looks nice! Any chance on getting this seperate and with an AUR package?

**Comment by XenGi** [comment] 2017-11-24 16:40
Not abandoned. Just out of the country for a while. Coming back in a few days and trying to get you some presents for Christmas. ;)

**Comment by Trollwut** [comment] 2017-11-24 20:23
Oh look at that rich boy going to vacations!

Hope you have a good time, cu soon :)

**Comment by XenGi** [comment] 2017-12-01 13:56
Closing this as it is covered by #9

**Comment by XenGi** [comment] 2017-12-01 14:58
This still doesn't work. The problem is that in the current pacaur version the indicator if a package is outdated is just the color of the version string. I haven't found a good way to parse this in Python yet.
If you guys have an idea I'm happy to hear it. :)

**Comment by Trollwut** [comment] 2017-12-01 18:53
I'm currently on it and already found a solution :)

TBH I'm a little proud of myself, because this is the first time playing around with Python :D 

Ok, I'm a GutHub noob. What would be the best way to propose a change for you? Is this where I fork your repo to my own account and then do a pull request? If so, could you give me a howto to that? :D

**Comment by Trollwut** [comment] 2018-01-26 20:48
Any update on this?

**Comment by XenGi** [comment] 2018-02-02 23:14
merged into master will update the AUR package now. Thx for the patch!

**Closed by XenGi** 2018-02-02 23:14 UTC
